### ISSUE TITLE
Buttons in admin page need to resize when window switches to narrow layout

### ISSUE THREAD

**Issue by reeserj** [coordinape/coordinape#1011]
**Summary:**

1. **What is actually happening:**
When the screen resizes to narrow the text in the buttons goes to 2 rows but the buttons don't grow to accommodate the new row
![image](https://user-images.githubusercontent.com/82838264/172485845-30fd7a96-e336-4304-abbd-25ce2942b49d.png)

2. **What should be happening:**
The buttons and button labels should get smaller to accommodate the narrower screen size and remain clear to read while also retaining a "normal" button look (not weirdly stretched or with stacked labels)

3. **Steps to recreate:**

- Go to admin page 
- Shrink window down until the header changes

_Comment below if you want to take this issue and it will be assigned to you._

**Comment by levity** [comment]
Maybe when the screen’s narrower we should switch to a smaller button size…
changing button height will look weird, I think, if some buttons but not
all of them become double-height.

**Comment by sshmm** [comment]
I think the button should remain inside the Panel too
![image](https://user-images.githubusercontent.com/34943689/173888210-c5b9cf2e-b546-459b-a746-a42e84004e1f.png)

**Comment by sshmm** [comment]
@levity what do you think about something like that 
![image](https://user-images.githubusercontent.com/34943689/173892226-244437fc-37be-4970-8ac8-cb937f556da8.png)
wrapping the buttons. also I made them all the same minWidth so that they will align
![image](https://user-images.githubusercontent.com/34943689/173892421-f0589886-f42e-419b-8da7-4fd4ff162d0f.png)

**Comment by levity** [comment]
That looks good to me!
