### ISSUE TITLE
Improve Circle Logo Upload Pattern

### ISSUE THREAD

**Issue by reeserj** [coordinape/coordinape#1497]
### What's happening:
Uploading images is a difficult user flow
### What should be happening
Uploading images should follow the add Org image process flow

1.  Button to upload new Image
![Image](https://user-images.githubusercontent.com/82838264/195173297-965a9ba0-dcf9-4fe5-8303-eae7bc7e9a62.png)
2. Auto-save Image after selected 
![Image](https://user-images.githubusercontent.com/82838264/195173477-3531e2f1-ec6e-42ce-8022-5b7c47faf2dc.png)
3. Error state
- If image too large return error : The maximum image size is 3mb, please try again with a smaller file.
4. While the image is uploading please give an indication that it's loading where the image saved text is "Saving..."

See #1496

**Comment by sshmm** [comment]
@wingfeatherwave @reeserj  
![image](https://user-images.githubusercontent.com/34943689/195714233-c90ba2a0-6144-4598-83c1-deee9d2c3eba.png)
update circle logo is part of circle settings. after logo is uploaded we need to click save settings to save the link to hasura.
this is not much different from the target behavior in the issue except for some checks

**Comment by crabsinger** [comment]
@sshmm since the underlying code uses a separate API endpoint `updateCircleLogo` I think it would be preferable behavior that the Circle Logo automatically uploads and saves when you select a new file (same behavior as Org and Profile page). We should show "Circle Logo Saved" as text when this completes.

Ideally, we also make sure that this doesn't dirty the Circle Settings Page form and it is kind of separate from that other form.

If there are issues or complexities to this approach, than something similar may be reasonable, but if this can work, this would be the preferred approach you should try for now.

Any other questions on this or does this make sense?
