### ISSUE TITLE
Web3 Wallet Explainer Interstitial Modal (For MagicLink)

### ISSUE THREAD

**Issue by ashmbanks** [coordinape/coordinape#1805]
- right before you start using MagicLink, a modal pops up
- information on what’s going on: [Still needs copy]
- e.g. “what am i signing?”
    - deeper doc (Gitbook) linked from modal (just create a stub at first)
        - what is gas?
        - will i need cryptocurrencies?
        - etc.
        - nice-to-have: link to some onboarding experiences made by frens (e.g. rabbithole?)

**Comment by ashmbanks** [comment]
@Zemm111  - I think that you had mentioned doing a first pass on Copy for this modal- is that right? If so, do you have something? If not, lmk, so we can do something else.

**Comment by Zemm111** [comment]
@ashmbanks I don't have it yet, but can work on it tomorrow - does that work?

**Comment by Zemm111** [comment]
@levity @ashmbanks 

Welcome to Coordinape, via Email Login.  

Because this is a Web3 application, it relies on an Ethereum (or EVM) wallet address. It seems like you don’t have one already, which is why you are logging in by email. So, we’ve made one for you.  

Your Coordinape wallet address is provided by [magic.link](http://magic.link/), an instant wallet provider that manages authentication for you.   

When you see popups about signing with your magic link wallet, that is what you are using.  You can also receive tokens from Coordinape CoVaults to this wallet, and interact with the blockchain in other ways.

  If, at any time, you wish to export this wallet to self manage it with a more flexible tool like MetaMask, you can do so by logging into [magic.link](http://magic.link/).

  For more information on wallets, web3, [magic.link](http://magic.link/) and a few best practices to maintain, please read here <link to docs>.  

If this all sounds good, please proceed!

<button to continue>

**Comment by levity** [comment]
Trimmed it down a bit. In particular, I removed the bit about exporting because we actually need to build that as a popup within our own app; it doesn't happen on magic.link's site. Sorry if I misspoke there.

<img width="682" alt="Screen Shot 2023-01-12 at 9 37 49 AM" src="https://user-images.githubusercontent.com/193667/211955235-bc8ad4ec-1f6b-4b3f-a705-019935569180.png">

**Comment by levity** [comment]
Also created a docs page: https://docs.coordinape.com/info/documentation/email-login-and-web3-best-practices

@Zemm111 maybe you want to flesh that out?

**Comment by Zemm111** [comment]
Def!  Have these on my list to look at tomorrow

**Comment by Zemm111** [comment]
Modal looks pretty good!

**Comment by ivyquinzel** [comment]
I would like to know if we could magic for all logins vs. just email. This would give a more unified login experience. If not, maybe more "designed" onboarding https://cdn.discordapp.com/attachments/1065728829022294048/1065750735532347492/CleanShot_2023-01-19_at_14.51.50.gif

**Comment by levity** [comment]
It’s too big of a lift to change over right now, since we just added
support for a number of chains.

**Comment by ivyquinzel** [comment]
> It’s too big of a lift to change over right now, since we just added support for a number of chains.
> […](#)
> On Fri, Jan 20, 2023 at 6:43 AM ivy ***@***.***> wrote: I would like to know if we could magic for all logins vs. just email. This would give a more unified login experience. If not, maybe more "designed" onboarding https://cdn.discordapp.com/attachments/1065728829022294048/1065750735532347492/CleanShot_2023-01-19_at_14.51.50.gif — Reply to this email directly, view it on GitHub <[#1805 (comment)](https://github.com/coordinape/coordinape/issues/1805#issuecomment-1397707466)>, or unsubscribe <https://github.com/notifications/unsubsc
<img width="806" alt="Screenshot 2023-01-20 at 8 01 01 PM" src="https://user-images.githubusercontent.com/92177509/213840960-2b572c6f-2715-4c49-9a89-92fca8c0cd63.png">
ribe-auth/AABPJA2SYUASNDSTQQCNTDDWTG7P3ANCNFSM6AAAAAATSQYAFU> . You are receiving this because you modified the open/close state.Message ID: ***@***.***>

Low lift version
