### ISSUE TITLE
When vouches required changes all pending vouchees should have their required vouches updated

### ISSUE THREAD

**Issue by reeserj** [coordinape/coordinape#288]
Issue discovered in the Coordinape Contributors Circle. 

1.Vouches were set at 5 and then 2 users were nominated.

1. Vouches were changed to 3 and 2 
2. Expected outcome: prior users should have had their vouches adjusted to 3 vouches required instead of 5
3. Actual Outcome: Prior users vouches remained at 5, and subsequent users required 3 vouches

**Comment by zashton** [comment]
Can imagine different people would have different expectations of the expected outcome.

Would there be a use case of an admin wanting to create nominations of different vouch requirements ?

Does the length of nomination reset to the new setting ? What happens if the nominee has already past that length?
Does the nominee get auto add into the circle if you adjust to 3 vouches and he already has 4 ? what will happen to the 4th vouch ? should we delete it ?

@reeserj

**Comment by reeserj** [comment]
Thanks for the ?'s @zashton.

In my opinion 
I don't think our admins would want to create nominations with different vouching requirements. 
I would expect the length of the nominations to reset to the new settings (EG if it changed from 5 days to 4 they'd all update to be 4 days and any nominations older than the new date would expire) 
Yes if the vouches changed from 5 to 3 and a user had 4 they'd be added.

I'm open to leaving that unneeded 4th vouch unless it breaks something?

Again these are only my opinions, and they're loosely held.

**Comment by levity** [comment]
@zashton I also wonder what people's expectations are. Let's not prioritize this change now; we can leave the issue open to let circle admins weigh in with their opinions.
