### ISSUE TITLE
Edit background doesn't work with file over 1 MB and no message about why

### ISSUE THREAD

**Issue by spydermonkee** [coordinape/coordinape#390]
**Problem**
When uploading a new background and image is larger than 1 MB (it seems), upload fails and message is minimal to user ("Network Error")

1. Nav to profile
2. choose edit background button
2. choose file larger than 1 MB and see preview on background 
3. click "Upload background" 

**RESULT** background does not update and small, red banner showing "Network Error" appears in bottom left of screen. In dev console, one can see 413 network error (Payload too large) 

**EXPECTED** - background update or message stating that file is big with acceptable file limit

Note: got this error when trying 1.1mb file, 1.7mb file, and 10+mb file
Note: 72kb successfully updated, 890kb successfully updated

![Screen Shot 2022-01-03 at 3 39 57 PM](https://user-images.githubusercontent.com/5608004/147992785-29382dc4-e486-4ea1-a77b-4bca8f41bdf0.png)

**Solution**
Propose a clearer message: 
"File too large. Please upload a file that is less than 1 MB"

Also propose a larger limit. 

**Stakeholders**
Dev team, Design team

**Comment by CryptoGraffe** [comment]
I can make some improvements here

**Comment by csggene3** [comment]
Hello, hoping to add some further information to what I'm seeing with respect to this issue. This could actually be (and is likely upon further review) a separate issue, but with the same end result. 

**Problem**
When uploading a new background, this one being 19kb, upload fails and message is minimal to user ("Network Error")
Console indicates code 500 (Internal server error)

**Context**
Image file is of type JFIF
![Screenshot 2022-01-09 063701](https://user-images.githubusercontent.com/10295641/148687019-4cb0ab06-33a0-491f-ba9c-bb4f9317964c.png)
I stepped through the Stack Trace option until finding what probably should have been an obvious assumption with the odd file type; that being the file type is not listed under the accepted types. I'm assuming this is the source of my error, but probably not the original opened issue?
![Screenshot 2022-01-09 065519](https://user-images.githubusercontent.com/10295641/148687757-acbd9c3d-71d3-467c-9c8e-959126935f7c.png)

But at the same time, I can't see why this would potentially be a problem to allow another file type seeing as how the preview function accepted it readily enough, and would allow files of a potentially much smaller size.
![Screenshot (14)](https://user-images.githubusercontent.com/10295641/148687043-14ddc969-3e97-422d-ac58-bd0551d0f5f9.png)
I have not tried to run my own instance of the program to add this JFIF file type to the "accept" list and see if this issue goes away since I have little experience with any of this. I had never used Stack Trace, and have very little experience with the console, but will try to get my own instance up and running to play with this small, obviously pretty inconsequential issue if doing so might be utilitarian. Apologies again if this should have been created as it's own issue. Please forgive my lack of experience and knowledge of procedure.

**Comment by CryptoGraffe** [comment]
@csggene3 I think if we want to support JFIF files (fairly uncommon) or at least have a better error we need a separate ticket.

**Comment by CryptoGraffe** [comment]
Diving into this unfurled a few different issues. The 1MB limit is actually an nginx config parameter. It's easily raised by adding this to the top level of the nginx conf for laravel, at the top, outside the server section:

```
client_max_body_size 20M;
```

I'm not entirely sure if we want this, or what the limit should be, but 1MB is extremely low for image upload. 

The secondary issue that I hit is that when this limit is reached, nginx returns a proper 204 to the OPTIONS preflight, but the way the error comes through on the POST it still results in a CORS error in axios. This means we don't get the http response and status code, so we can't trap on the HTTP Status 413. It's a bit strange, because the Network tab in chrome shows the 413, but axios loses it and chrome also logs a CORS error.  There is a [related issue](https://github.com/fruitcake/laravel-cors/issues/306) in the `laravel-cors` library, but I don't think there is actually a problem on their end, since 413 seems to make it back to the browser. 

I suspect the issue is that despite preflight working (because laravel runs that), nginx is catching the too-large-payload and  throwing the 413 without the `Access-Control-Allow-Origin` header, because it usually doesn't control that, laravel does. 

The third issue I hit here is that when I got this all working, the current local dev setup gets a 500 error on any file upload. I am not savvy enough with the setup and laravel to figure out how to read the full logs (or enable debugging), but would like to get up to speed on that.

**Comment by exrhizo** [comment]
Thank you for looking into this, @f1lander was also having this happen with the 500 on upload locally, I don't know what is needed for that, I thought of setting up [fake docker s3](https://github.com/jubos/fake-s3).

I am impressed you deduced the thing with nginx and cors, I imagine that was confusing

The thing that I would recommend here is to add the check before the request is made.

For example in `AvatarUpload`

```
export const AvatarUpload = ({
  original,
  commit,
}: {
  original?: string;
  commit: (file: File) => Promise<any>;
}) => {
```

Wrap commit in a function and then call `const { apeError } = useApeSnackbar();` if the file is wrong.

Same idea for the background,
in `ProfilePage`, `FormFileUpload` have `commit.catch(apeError)`

Or something like that

**Comment by CryptoGraffe** [comment]
@exrhizo Yes the CORS thing was a bit of a spelunk, and I thought I was going crazy for a bit there. 

Re: the browser side size check, that was what I was planning after we settle on a limit. The bummer is that the constant for this has to be in two repos/places, rather than just handling the lovely 413 error. 

I was wondering if we could add conditional CORS config to nginx that it would use in the case of the 413, e.g. just for these routes, or only if the Access-Control-Header isn't set, but this seems all a bit much just for avatar/background uploads, so the file size limit in the browser is probably fine. If we did want to go this route, this nginx plugin might be a good fit https://github.com/openresty/headers-more-nginx-module#more_set_headers . I'm not an nginx expert.

**Comment by CryptoGraffe** [comment]
@exrhizo For raising the limit in laravel, should I make an issue/PR for that?

**Comment by CryptoGraffe** [comment]
Went ahead and made the PR in the backend

**Comment by CryptoGraffe** [comment]
@exrhizo I found a much better solution that fakes3 called [LocalStack](https://github.com/localstack/localstack) . They already have docker images and everything. Fakes3 is not really maintained anymore, doesnt have docker images, and also now requires a license. I had gone and built a docker image for it etc but then stumbled on LocalStack. Pretty cool project.
