### ISSUE TITLE
Profile image not showing on map view or allocation page

### ISSUE THREAD

**Issue by spydermonkee** [coordinape/coordinape#417]
**Problem**
User updated profile image and profile image is not updated on map or on allocate page. 

**Map view:**
<img width="330" alt="profile pic problem" src="https://user-images.githubusercontent.com/5608004/149437220-e625acb2-b18a-427f-a9b4-6c862807d0a2.png">
**Allocation page view:**
<img width="349" alt="profile pic problem2" src="https://user-images.githubusercontent.com/5608004/149437226-cd546146-417f-4091-a3b5-ae127e54b9d2.png">

Tried this in Firefox and Chrome.

**Comment by f1lander** [comment]
It's weird that just user has that behavior, let me check, I'll try to reproduce and what's going on

**Comment by f1lander** [comment]
Regarding the issue of the pfp in the map I posted this before regarding to the pfp issue as you see some of the pfp are getting forbidden https://discord.com/channels/845400066532704256/889914376490983454/932682234371141672

To be sure I want to see the policies about that in the s3 bucket, I just made a test with a s3 bucket, enabling public access to for the object specifically and I did not get the forbidden 403 error.

The thing is this seems happening like accessing like multiple times o random because issue is not that the pfp can't be load at all, just when we try to get the url and load it into the map object node, and for just specific images we're getting the 403.

Resources:
https://aws.amazon.com/premiumsupport/knowledge-center/s3-403-forbidden-error/?nc1=h_ls

![image](https://user-images.githubusercontent.com/5679878/150871079-9fbab5de-3b6e-4c90-a9a5-f5ef36f3340b.png)
