### ISSUE TITLE
LOCAL var mismatches in seeding scripts

### ISSUE THREAD

**Issue by CryptoGraffe** [coordinape/coordinape#464]

**Comment by exrhizo** [comment]
temp solution add:
`NODE_HASURA_ADMIN_SECRET=admin-secret`

**Comment by exrhizo** [comment]
https://github.com/coordinape/coordinape/pull/472

**Comment by exrhizo** [comment]
I don't know what the best thing would be, because this `api-lib` vars are used by both the serverless functions, therefore they need the NODE_HASURA_URL prefix. But when used for the local scripts, they should be set to the local versions....

There is a bigger question, which is what should the interface to the gql code look like
`src/lib/gql/index.ts` is user scoped
`src/lib/gql/GqlHasuraAdmin.ts` is admin scoped

@levity you changed the `src/lib/gql/index.ts` to be strictly tied to 
`import { getAuthToken } from 'services/api';`
That is complecting it with our react app, ideally it would be an independent package

I did a kind of stand in solution but these interfaces could really use work

**Comment by exrhizo** [comment]
I didn't mean to close this, I am not good at github issues yet
