### ISSUE TITLE
Org View: Change nav

### ISSUE THREAD

**Issue by spydermonkee** [coordinape/coordinape#555]
**Specification**
- Add Circles Link to left part of nav bar
- Add History to nav bar (link to existing History page)
- Right Justify existing nav 
- Add Breadcrumb when in circle ("ORG NAME">"CIRCLE NAME")
- Remove redundant links from the Avatar Dropdown menu ("My History", "My Team", "Add Circle", "My Epoch", Circles - Note that the circle selection is replaced by https://github.com/coordinape/coordinape/issues/554)
 

**Note that the "Funding" nav item will not be present in the first version of ORG VIEW that gets released before VAULTS. (Even though the figma design shows the "Funding" nav item currently.)

https://www.figma.com/file/wXF7xGVv1j2SqwWfgbamS8/App-1.0?node-id=3987%3A15460

**Note that the the whole milestone of [ORG VIEW  ](https://github.com/coordinape/coordinape/milestone/5) should be released together on the app. These changes need to be released as one new feature :)

**Comment by MarcogodoyV** [comment]
@spydermonkee @levity I would like to take this issue and I saw that the issues of this milestone have to be reseale all at once.  Is it possible to get assign to all 3?

**Comment by levity** [comment]
@MarcogodoyV the plan is for @f1lander to look into this after he's done with #541, but you can feel free to jump in if you want. 

Re "These changes need to be released as one new feature", I've created a branch in the repo called `org-view`. You can create PRs that use that branch as a base instead of `main`, so we can merge work-in-progress to `org-view`, but wait until it's all done before merging it all to `main`. Does that make sense?

**Comment by MarcogodoyV** [comment]
@levity if the plan is for @f1lander I'd prefer to ask him first. I can take another issue to work on if you prefer that, I'm ready to code and want to contribue as much as I can.

**Comment by levity** [comment]
> @levity if the plan is for @f1lander I'd prefer to ask him first. I can take another issue to work on if you prefer that, I'm ready to code and want to contribue as much as I can.

Actually, it would be great if you could start working on this one before #556. @f1lander is still working on #541, and this one would be great to get implemented ASAP so we can start getting internal feedback from team members. IMO this is higher priority than #556 since it touches the global navbar, and #556 is a single page of changes. (@spydermonkee lemme know if you think otherwise)

**Comment by spydermonkee** [comment]
Hi, @MarcogodoyV !

Have you had a chance to dig into this? Would love to hear how it's going for you :)

**Comment by MarcogodoyV** [comment]
@spydermonkee hi!, yep I did, I only have to grab the style from the nav bar and put it into the new circle item, I had to make a few changes to put it in the left part of the bar and keep the other part in the right (they're working as different navs

**Comment by spydermonkee** [comment]
Awesome! Glad to hear about the progress! Look forward to checking in next week :)

**Comment by spydermonkee** [comment]
@MarcogodoyV - If you're interested to pick up #554, please put a comment on there and I'll assign you. I'm happy to have a call with you to coordinate more closely if that would be helpful :)

**Comment by crabsinger** [comment]
Closing.COmpleted by 555
