### ISSUE TITLE
"Coordinape In Your Circle": Tooltip and link in Teammates view

### ISSUE THREAD

**Issue by spydermonkee** [coordinape/coordinape#560]
**Problem**
We've added a Coordinape user in all circles to enable people to give to Coordinape if they feel inspired as a token of thanks or just to support Coordinape. The problem is that we have not given our Coordinape Humans enough context as to what this is all about and many admins have simply deleted it. Others have ignored. A few have given to Coordinape! 

**Specification**
- Add tooltip link ("Why is Coordinape in my circle?") and tooltip list in the Teammates view. 
- Link on tooltip ("Let us know what you think")) goes here: https://coordinape.notion.site/Why-is-Coordinape-in-my-Circle-fd17133a82ef4cbf84d4738311fb557a

Design: 
https://www.figma.com/file/Db8KthuZRjT5CfMvZsjTT2/Coordinape-Design-v7?node-id=2731%3A10174

**Comment by j-yw** [comment]
taking this

**Comment by levity** [comment]
Hey @j-yw, I'm leaving some feedback here instead of on #571 because it's more about the design than the code.

I see there's some ambiguity in the Figma, because it doesn't show that the Save Teammates List button actually floats above the rest of the page's content as you scroll. I don't think the designers' intention was that the "Why is Coordinape in my circle?" link should do the same thing, because it can end up with situations like this:

![Screen Shot 2022-03-01 at 6 42 17 PM](https://user-images.githubusercontent.com/193667/156284704-9073b277-142d-4388-a51a-5d375ef123c5.png)

I'm guessing it should go at the bottom of the page's content area instead, after the opted-out users.

**Comment by j-yw** [comment]
> 

Maybe the location of this tooltip should be changed? putting it at the bottom of the allocation page creates a white bar across the page which is not ideal.

**Comment by j-yw** [comment]
I found a potential fix by modifying the .body wrapper slightly. The tooltip is fixed to the bottom now and doesn't scroll with the button.
